/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PengelolaanKRS;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class TabelMataKuliah extends javax.swing.JFrame {
    DefaultTableModel mod;
    private String SQL;
    
    /** Creates new form TabelMataKuliah */
    public TabelMataKuliah() {
        initComponents();
        matakuliah();
        tampilandata();
        setLocationRelativeTo(this);
        
    }
    
    private void matakuliah(){
        textid.setText(null);
        textnama_makul.setText(null);
        textkelas.setText(null);
        textsemester.setText(null);

    }
    
    private void tampilandata(){
        mod = new DefaultTableModel();
        mod.addColumn("Id");
        mod.addColumn("Nama_Matkul");
        mod.addColumn("Kelas");
        mod.addColumn("Semester");
        tabelmatakuliah.setModel(mod);
        Connection conn=Koneksi.getConnection();
        try{
            java.sql.Statement smt = conn.createStatement();
            SQL = "select*from tb_matakuliah";
            java.sql.ResultSet res = smt.executeQuery(SQL);
            while(res.next()){
                mod.addRow(new Object[]{
                    res.getString("Id"),
                    res.getString("Nama_Matkul"),
                    res.getString("Kelas"),
                    res.getString("Semester"),
                });
                }
            }catch (SQLException e) {
                System.out.println(e);
        }
        
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btncreate = new javax.swing.JButton();
        btnread = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        textid = new javax.swing.JTextField();
        textnama_makul = new javax.swing.JTextField();
        textkelas = new javax.swing.JTextField();
        textsemester = new javax.swing.JTextField();
        btnkeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelmatakuliah = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Pictures\\aulia bc 2.png")); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Pictures\\aulia bc 2.png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jLabel1.setText("DATA MATA KULIAH");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Id");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 170, 29));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nama_Makul");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 172, 28));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Kelas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 172, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Semester");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 172, 31));

        btncreate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncreate.setText("CREATE");
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });
        jPanel1.add(btncreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        btnread.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnread.setText("READ");
        btnread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreadActionPerformed(evt);
            }
        });
        jPanel1.add(btnread, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, -1, -1));

        btndelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, -1, -1));
        jPanel1.add(textid, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 300, 30));

        textnama_makul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnama_makulActionPerformed(evt);
            }
        });
        jPanel1.add(textnama_makul, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 300, 30));
        jPanel1.add(textkelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 300, 30));
        jPanel1.add(textsemester, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 300, 30));

        btnkeluar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnkeluar.setText("KELUAR");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, -1, -1));

        tabelmatakuliah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nama_Makul", "Kelas", "Semester"
            }
        ));
        tabelmatakuliah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelmatakuliahMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelmatakuliah);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 640, 90));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PengelolaanKRS/aulia bc 2.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textnama_makulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnama_makulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnama_makulActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        MenuUtama xx;
        xx = new MenuUtama();
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
       try{
           Connection conn = Koneksi.getConnection();
           PreparedStatement smt = conn.prepareStatement
           ("insert into tb_matakuliah (Id, Nama_Matkul,Kelas,Semester)value(?,?,?,?)");
           smt.setString(1, textid.getText());
           smt.setString(2, textnama_makul.getText());
           smt.setString(3, textkelas.getText());
           smt.setString(4, textsemester.getText());
           smt.executeUpdate();
           JOptionPane.showMessageDialog(null, "Data Sukses Ditambahkan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
           tampilandata();
           matakuliah();
           
           
        }catch (SQLException e){
            System.out.println(e);
        }                                 
    }//GEN-LAST:event_btncreateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        int i = tabelmatakuliah.getSelectedRow();
        if(i == -1){
            return;
        }
        
        String Id = (String)mod.getValueAt(i, 0);
        
        int question =JOptionPane.showConfirmDialog(null, "Yakin Data Akan Terhapus?","Konfirmasi", JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(question == JOptionPane.OK_OPTION){
        try{
            Connection conn = Koneksi.getConnection();
            String sql = "DELETE FROM tb_matakuliah WHERE Id = ?";
            try (PreparedStatement p = conn.prepareStatement(sql)) {
                String id = null;
                p.setString(1, Id);
                p.executeUpdate();
            }
            JOptionPane.showMessageDialog(null,"Data Berhasil Terhapus");
            
        }catch(SQLException e){
            System.out.println(e);
        }
    }
        if(question == JOptionPane.CANCEL_OPTION){
    }                                         
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreadActionPerformed
        try{
           Connection conn = Koneksi.getConnection();
           PreparedStatement smt = conn.prepareStatement
           ("insert into tb_matakuliah (Id, Nama_Matkul,Kelas,Semester)value(?,?,?,?)");
           smt.setString(1, textid.getText());
           smt.setString(2, textnama_makul.getText());
           smt.setString(3, textkelas.getText());
           smt.setString(4, textsemester.getText());
           smt.executeUpdate();
           JOptionPane.showMessageDialog(null, "Data Sukses Disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
           tampilandata();
           matakuliah();
           
           
        }catch (SQLException e){
            System.out.println(e);
        }                                 
    }//GEN-LAST:event_btnreadActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        try{
            String sql = "UPDATE tb_matakuliah SET Nama_Matkul ='"+textnama_makul.getText()+"', Kelas='"+textkelas.getText()+"', Semester='"+textsemester.getText()+"' WHERE Id = '"+textid.getText()+"'";
            java.sql.Connection conn=(Connection) Koneksi.getConnection();
            java.sql.PreparedStatement smt = conn.prepareStatement(sql);
            smt.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Update");
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal di SImpan"+e.getMessage());
        }
        tampilandata();
        matakuliah();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void tabelmatakuliahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelmatakuliahMouseClicked
        try{
             Connection conn = Koneksi.getConnection();
             int row = tabelmatakuliah.getSelectedRow();
             String tabel_klik = (tabelmatakuliah.getModel().getValueAt(row, 0).toString());
             java.sql.Statement smt = conn.createStatement();
             java.sql.ResultSet sql = smt.executeQuery("select * from tb_matakuliah where Id = '"+tabel_klik+"'");
              
             if (sql.next()){
                 String Id=sql.getString("Id");
                 textid.setText(Id);
                 String Nama_Matkul=sql.getString("Nama_Matkul");
                 textnama_makul.setText(Nama_Matkul);
                 String Kelas=sql.getString("Kelas");
                 textkelas.setText(Kelas);
                 String Semester=sql.getString("Semester");
                 textsemester.setText(Semester);
                 
             }
             
             }catch (SQLException e){}
    }//GEN-LAST:event_tabelmatakuliahMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelMataKuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TabelMataKuliah().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncreate;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnread;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelmatakuliah;
    private javax.swing.JTextField textid;
    private javax.swing.JTextField textkelas;
    private javax.swing.JTextField textnama_makul;
    private javax.swing.JTextField textsemester;
    // End of variables declaration//GEN-END:variables

}
