/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PengelolaanKRS;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author ASUS
 */
public class tb_mahasiswa extends javax.swing.JFrame {
DefaultTableModel mod;
private String SQL;
    /**
     * Creates new form tb_mahasiswa
     */
    public tb_mahasiswa() {
        initComponents();
        mahasiswa();
        tampilandata();
        setLocationRelativeTo(this);
    }
    private void mahasiswa(){
        textnpm.setText(null);
        textnama.setText(null);
        textkelas.setText(null);
        textfakultas.setText(null);
        textprodi.setText(null);
    }
    private void tampilandata(){
        mod = new DefaultTableModel();
        mod.addColumn("NPM");
        mod.addColumn("Nama");
        mod.addColumn("Kelas");
        mod.addColumn("Fakultas");
        mod.addColumn("Prodi");
        tabelmahasiswa.setModel(mod);
        Connection conn=Koneksi.getConnection();
        
        try{
            java.sql.Statement smt = conn.createStatement();
            SQL = "select * from tb_mahasiswa";
            java.sql.ResultSet res = smt.executeQuery(SQL);
            while(res.next()){
                mod.addRow(new Object[]{
                    res.getString("NPM"),
                    res.getString("Nama"),
                    res.getString("Kelas"),
                    res.getString("Fakultas"),
                    res.getString("Prodi")
                    
                });
            }
        }catch (SQLException e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textnpm = new javax.swing.JTextField();
        textnama = new javax.swing.JTextField();
        textkelas = new javax.swing.JTextField();
        textprodi = new javax.swing.JTextField();
        textfakultas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelmahasiswa = new javax.swing.JTable();
        btnread = new javax.swing.JButton();
        btncreate = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btncetak = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("NPM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 93, 111, 23));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nama");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 141, 111, 23));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Kelas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 187, 111, 22));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Fakultas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 238, 111, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Prodi");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 278, 111, 22));
        jPanel1.add(textnpm, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 92, 294, 27));
        jPanel1.add(textnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 138, 294, 31));
        jPanel1.add(textkelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 187, 294, 27));

        textprodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textprodiActionPerformed(evt);
            }
        });
        jPanel1.add(textprodi, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 272, 294, 29));
        jPanel1.add(textfakultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 232, 294, 28));

        tabelmahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NPM", "Nama", "Kelas", "Fakultas", "Prodi"
            }
        ));
        tabelmahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelmahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelmahasiswa);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 380, 665, 106));

        btnread.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnread.setText("READ");
        btnread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreadActionPerformed(evt);
            }
        });
        jPanel1.add(btnread, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 339, -1, -1));

        btncreate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncreate.setText("CREATE");
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });
        jPanel1.add(btncreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 339, -1, -1));

        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnupdate.setText("UPDATE");
        btnupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnupdateMouseClicked(evt);
            }
        });
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 339, -1, -1));

        btndelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 332, -1, -1));

        btncetak.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncetak.setText("CETAK");
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });
        jPanel1.add(btncetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(721, 219, 93, -1));

        btnkeluar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnkeluar.setText("KELUAR");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(721, 178, 93, -1));

        jLabel6.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jLabel6.setText("DATA MAHASISWA");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 29, 276, 36));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PengelolaanKRS/aulia bc 2.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
        try{
            Connection conn = Koneksi.getConnection();
            PreparedStatement smt = conn.prepareStatement
            ("insert into tb_mahasiswa (NPM, Nama, Kelas, Fakultas, Prodi) value(?, ?, ?, ?, ?)");
            smt.setString(1, textnpm.getText());
            smt.setString(2, textnama.getText());
            smt.setString(3, textkelas.getText());
            smt.setString(4, textfakultas.getText());
            smt.setString(5, textprodi.getText());
            smt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Ditambah","Pesan",JOptionPane.INFORMATION_MESSAGE);
            tampilandata();
            mahasiswa();
        }catch (SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btncreateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
     int i = tabelmahasiswa.getSelectedRow();
     if (i == -1){
         return;
     }
     
     String NPM = (String)mod.getValueAt(i, 0);
     
     int question = JOptionPane.showConfirmDialog(null, "Yakin Data Ingin Dihapus?","Konfirmasi", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
     if(question == JOptionPane.OK_OPTION){
         try{
             Connection conn = Koneksi.getConnection();
             String sql = " DELETE FROM tb_mahasiswa WHERE NPM = ?";
             try (PreparedStatement p = conn.prepareStatement(sql)){
                 String npm = null;
                 p.setString(1, NPM);
                 p.executeUpdate();
             
             }
             JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
         }catch(SQLException e){
             System.out.println(e);
         }
     }
     
     if (question == JOptionPane.CANCEL_OPTION){
         
     }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreadActionPerformed
        try{
            Connection conn = Koneksi.getConnection();
            PreparedStatement smt = conn.prepareStatement
            ("insert into tb_mahasiswa (NPM, Nama, Kelas, Fakultas, Prodi) value(?, ?, ?, ?, ?)");
            smt.setString(1, textnpm.getText());
            smt.setString(2, textnama.getText());
            smt.setString(3, textkelas.getText());
            smt.setString(4, textfakultas.getText());
            smt.setString(5, textprodi.getText());
            smt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            tampilandata();
            mahasiswa();
        }catch (SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnreadActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        MenuUtama xx;
        xx = new MenuUtama();
        xx.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void textprodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textprodiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textprodiActionPerformed

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
       try{
           JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("report1.jasper"), null, Koneksi.getConnection());
           JasperViewer.viewReport(jp, false);
       
       }catch (JRException e){
           JOptionPane.showMessageDialog(rootPane, e);
       }
    }//GEN-LAST:event_btncetakActionPerformed

    private void tabelmahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelmahasiswaMouseClicked
         try{
             Connection conn = Koneksi.getConnection();
             int row = tabelmahasiswa.getSelectedRow();
             String tabel_klik = (tabelmahasiswa.getModel().getValueAt(row, 0).toString());
             java.sql.Statement smt = conn.createStatement();
             java.sql.ResultSet sql = smt.executeQuery("select * from tb_mahasiswa where NPM = '"+tabel_klik+"'");
              
             if (sql.next()){
                 String NPM=sql.getString("NPM");
                 textnpm.setText(NPM);
                 String Nama=sql.getString("Nama");
                 textnama.setText(Nama);
                 String Kelas=sql.getString("Kelas");
                 textkelas.setText(Kelas);
                 String Fakultas=sql.getString("Fakultas");
                 textfakultas.setText(Fakultas);
                 String Prodi=sql.getString("Prodi");
                 textprodi.setText(Prodi);
             }
             
             }catch (SQLException e){}
    }//GEN-LAST:event_tabelmahasiswaMouseClicked

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        try{
            String sql = "UPDATE tb_mahasiswa SET Nama ='"+textnama.getText()+"', Kelas='"+textkelas.getText()+"', Fakultas='"+textfakultas.getText()+"', Prodi='"+textprodi.getText()+"' WHERE NPM = '"+textnpm.getText()+"'";
            java.sql.Connection conn=(Connection) Koneksi.getConnection();
            java.sql.PreparedStatement smt = conn.prepareStatement(sql);
            smt.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Update");
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal di SImpan"+e.getMessage());
        }
        tampilandata();
        mahasiswa();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateMouseClicked
     
    }//GEN-LAST:event_btnupdateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tb_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    //</editor-fold>
    
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new tb_mahasiswa().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncetak;
    private javax.swing.JButton btncreate;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnread;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelmahasiswa;
    private javax.swing.JTextField textfakultas;
    private javax.swing.JTextField textkelas;
    private javax.swing.JTextField textnama;
    private javax.swing.JTextField textnpm;
    private javax.swing.JTextField textprodi;
    // End of variables declaration//GEN-END:variables
}
